name: Créer un dépôt à partir du modèle

on:
  repository_dispatch:
    types: [create-repo]

jobs:
  create_repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2.5.0

    - name: Configurer GitHub CLI
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Configurer le jeton d'accès GitHub CLI"
        gh config set -h github.com oauth-token $GH_TOKEN

    - name: Créer le dépôt depuis le modèle
      run: |
        # Placez ici votre commande pour créer un dépôt à partir du modèle
        gh repo create exemple-test --template=students-com/exemple
